name: build-ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup-ocaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3.0
    - name: setup-dep
      run: |
        opam install . --deps-only --with-test --with-doc --with-dev-setup
    - name: install
      run: |
        opam exec -- dune build @install
    - name: fmt
      run: |
        opam exec -- dune build @fmt
    - name: runtest
      run: |
        opam exec -- dune build @runtest
